### PR TITLE
Add an installation instruction using nix

### PR DESCRIPTION
**Pull request by Ch1keen**
I have added an installation instruction using Nix package manager. https://github.com/ronin-rb/ronin-rb.github.io/issues/22

This will help people install ronin using Nix package manager.

### CODE REVIEW

**Review by postmodern — APPROVED** [review]
Thank you!

**Comment by postmodern** [comment]
I will begin writing the blog post and probably post it on Tuesday (May 30th) after Memorial Day weekend so that people will more likely see the blog post.

**Comment by Ch1keen** [comment]
> Thank you!

Blame my laziness. I hope I can do more contribution on the ronin project.

> I will begin writing the blog post and probably post it on Tuesday (May 30th) after Memorial Day weekend so that people will more likely see the blog post.

I'll look forward it. I'm so excited!

**Comment by postmodern** [comment]
@Ch1keen here is the rough draft of the blog post. I still need to add a paragraph explaining what is NixOS. Also not sure about whether to call it NixOS, Nix, or nixpkgs?
https://github.com/ronin-rb/ronin-rb.github.io/commit/dd4b89348f829a0067f39fd650d6b814762ccde6

**Comment by Ch1keen** [comment]
Just 'Nix' is enough I think. Nix is like an ecosystem, including `nix` command line tools, a programming language (Nix expression), `nixpkgs` and `NixOS` of course.

`nixpkgs` is a collection of packages, most of the definition is written in Nix language. NixOS is an attempt to make a Linux distribution with `nixpkgs` for hardcore Nix user.

Nix package manager can be used in the other Linux distribution like ubuntu, fedora, along with `apt` or `dnf`.

```diff
- title: Ronin now available on NixOS!
+ title: Ronin now available on Nix!
```

I made a PR to `nixpkgs` repository, so I did a contribution on Nix ecosystem, it makes users of Nix package manager and NixOS users install `ronin`.

**Comment by Ch1keen** [comment]
How about this simple explanation of Nix?

```text
[Nix](https://nixos.org) is a purely functional package manager which helps you manage packages in an uncluttered, declarative, and reproducible way.
```

the other sentence below is generated by BingAI. This focus on the technique.

```text
Nix is a cross-platform package manager that utilizes a purely functional deployment model where software is installed into unique directories generated through cryptographic hashes.
```

**Comment by postmodern** [comment]
@Ch1keen should `/install/nixos/` also be renamed to `/install/nix/`?

**Comment by Ch1keen** [comment]
It's like a cherry on top.

Shall I rename it?

**Comment by postmodern** [comment]
@Ch1keen sure thing, I'll wait for your PR.

**Comment by postmodern** [comment]
@Ch1keen alright, I have updated the blog post a bit:
https://github.com/ronin-rb/ronin-rb.github.io/compare/ea348286c2f9...560db56e5555

**Comment by Ch1keen** [comment]
`nix-env -iA ronin` won't work. It should be `nixpkgs.ronin` or `nixos.ronin` depend on the environment.
And I'd like to add another way to use `ronin` in nix:

```text
(...)

'''shell
nix-env -iA nixpkgs.ronin
'''

And if you want to use `ronin` in a virtual environment temporarily:

'''shell
nix-shell -p ronin
'''

(...)
```

By the way, the explanation of Nix looks so nice an perfect.

**Comment by postmodern** [comment]
@Ch1keen ah ha, I think you might want to send a PR to fix the Copy/Paste Instructions on `/install/nix/index.md`. That's where I copy/pasted `nix-env -iA ronin` from.
https://github.com/ronin-rb/ronin-rb.github.io/blob/main/install/nix/index.md#copypaste-instructions

**Comment by Ch1keen** [comment]
Oops. That's my bad.

**Comment by postmodern** [comment]
@Ch1keen ok updated the blog post to reflect those changes:
https://github.com/ronin-rb/ronin-rb.github.io/blob/d45b26773083cdcceaa6c60b678ef5c74e831779/blog/_posts/2023-05-30-ronin-now-available-on-nix.md

**Comment by Ch1keen** [comment]
Thank you so much!

**Comment by postmodern** [comment]
Blog post is now live! Thank you for the hard work.
https://ronin-rb.dev/blog/2023/05/30/ronin-now-available-on-nix.html

**Pull request merged**
