### PR TITLE
Update Getting Started Link

### PR DESCRIPTION
**Pull request by Smartmind12**
Related to #48 

Repairing Guides Link for the "Getting Started page"

### CODE REVIEW

**Review by postmodern — APPROVED** [review]

**Review by postmodern — CHANGES_REQUESTED** [review]
This mistake seems to be copied across all of the guides. I think you could fix them all in one PR.

```
docs/guides/getting-started/index.md:    <a class="button" href="../index.html#guides">
docs/guides/ruby-quick-ref/index.md:    <a class="button" href="../index.html#guides">
docs/guides/using-ronin-db/index.md:    <a class="button" href="../index.html#guides">
docs/guides/using-ronin-repos/index.md:    <a class="button" href="../index.html#guides">
docs/guides/using-the-ronin-cli/index.md:    <a class="button" href="../index.html#guides">
docs/guides/using-the-ronin-ruby-shell/index.md:    <a class="button" href="../index.html#guides">
docs/guides/writing-ronin-ruby-scripts/index.md:    <a class="button" href="../index.html#guides">
```

Also could use a more descriptive commit message, such as "Fixed the broken Guides links". Feel free to `git commit --amend` and `git push -f`. However, if it's easier for you to fix the Guides links one-by-one, I will accept individual PRs provided you fix them all.

**Comment by Smartmind12** [comment]
> This mistake seems to be copied across all of the guides. I think you could fix them all in one PR.
> 
> ```
> docs/guides/getting-started/index.md:    <a class="button" href="../index.html#guides">
> docs/guides/ruby-quick-ref/index.md:    <a class="button" href="../index.html#guides">
> docs/guides/using-ronin-db/index.md:    <a class="button" href="../index.html#guides">
> docs/guides/using-ronin-repos/index.md:    <a class="button" href="../index.html#guides">
> docs/guides/using-the-ronin-cli/index.md:    <a class="button" href="../index.html#guides">
> docs/guides/using-the-ronin-ruby-shell/index.md:    <a class="button" href="../index.html#guides">
> docs/guides/writing-ronin-ruby-scripts/index.md:    <a class="button" href="../index.html#guides">
> ```
> 
> Also could use a more descriptive commit message, such as "Fixed the broken Guides links". Feel free to `git commit --amend` and `git push -f`. However, if it's easier for you to fix the Guides links one-by-one, I will accept individual PRs provided you fix them all and use a more descriptive commit message.

Yes i understand and i will add more descriptive comments in the PR.

**Comment by postmodern** [comment]
> Yes i understand and i will add more descriptive comments in the PR.

I need more descriptive commit messages that describe your changes, which go into the git history.

**Comment by Smartmind12** [comment]
> > Yes i understand and i will add more descriptive comments in the PR.
> 
> I need more descriptive commit messages that describe your changes, which go into the git history.

Yes made the changes!

**Review by postmodern — APPROVED** [review]

**Comment by postmodern** [comment]
Hacktoberfest 2023 is now over! Congratulations on successfully submitting a PR to Ronin. As mentioned in the [blog post](https://ronin-rb.dev/blog/2023/09/26/ronin-is-participating-in-hacktoberfest-2023.html), you are now eligible for **free** [Ronin stickers](https://merch.ronin-rb.dev/category/stickers)! In order to claim your free stickers, please join the [Ronin Discord server](https://discord.gg/Cw5WWnycRH), and DM me the following information:

1. Which stickers do you want?
2. Your full mailing address.

The stickers will then be mailed in a regular flat-rate envelope, from the US, without tracking. Note, it may take up to one month for International mail to arrive.

**Pull request merged**
